name: SpilyaWarps
version: '2.0'
main: org.spilya.warpplugin.SpilyaWarps
description: Обычный плагин на варпы
author: Spilya and Stranik
api-version: '1.21'

commands:
  setwarp:
    permission: spilyawarp.set

  delwarp:
    permission: spilyawarp.delete

  warp:
    permission: spilyawarp.teleport
  
  listwarp:
    permission: spilyawarp.teleport

  delpwarps:
    permission: spilyawarp.delete

permissions:
  spilyawarp.commands:
    default: op
    children:
      - spilyawarp.set
      - spilyawarp.delete
      - spilyawarp.teleport
      - spilyawarp.delete
      - spilyawarp.teleport